Project1
Dema-koder/Tinkoff-course-2023 pull request #4
Opened 2023-10-20 03:24 UTC by Dema-koder

2023-10-24 16:47 UTC, ZhekTheDark requested changes

2023-10-24 16:47 UTC, ZhekTheDark commented on src/main/java/edu/project1/Repeat.java
> +record Repeat() implements Request {
зачем оно?

2023-10-24 16:47 UTC, ZhekTheDark commented on src/main/java/edu/project1/Request.java
> +public sealed interface Request permits Defeat, FailedRequest, Repeat, SuccessfulRequest, Win {
давай все имплементации соберем в одном пекедже

2023-10-24 16:47 UTC, ZhekTheDark commented on src/main/java/edu/project1/UserInfo.java
> +    private static char[] letters;
зачем нужны `doneAttempts` и `letters`?

2023-10-24 16:47 UTC, ZhekTheDark commented on src/main/java/edu/project1/Game.java
> +        if (letter < 'a' || letter > 'z') {
alt + enter -> simplify

2023-10-25 12:04 UTC, Dema-koder commented on src/main/java/edu/project1/Repeat.java
> +record Repeat() implements Request {
checkstyle ругается, говорит используй logger, а его не использую потому что игра консольная

2023-10-25 13:39 UTC, Dema-koder commented on src/main/java/edu/project1/UserInfo.java
> +    private static char[] letters;
Задавал поля, с идеей потом добавить функциональность, однако так и не добавил, сейчас удалю

2023-10-26 21:03 UTC, ZhekTheDark commented
хорошо, вливай в мастер

2023-10-26 21:13 UTC, merged